extends SceneTree

func _initialize():
	var stage = load("res://2_stage.gd").new()
	stage.phase_graph = GraphEdit.new()
	root.add_child(stage.phase_graph)
	stage._observe_phase(10, 0.0, 1.0)
	stage._observe_phase(11, 2.0, 1.0)
	stage._observe_phase(12, 2.0, 2.0)
	assert(stage.previous_motion_phase == 0)
	assert(stage.motion_enter_tick == 11)
	assert(stage.observed_edges.keys() == ["IDLE->DASH"])
	assert(stage.phase_graph.get_connection_list().size() == 1)
	stage._observe_phase(12, 2.0, 2.0)
	assert(stage.observed_edges.size() == 1)
	stage._observe_phase(12, 3.0, 1.0)
	assert(stage.observed_edges.is_empty())
	assert(stage.phase_graph.get_connection_list().is_empty())
	stage._observe_phase(8, 0.0, 1.0)
	assert(stage.previous_motion_phase == -1)
	assert(stage.phase_nodes.keys() == [0])
	for code in [-1.0, 12.0, 0.5, NAN, INF]:
		stage._observe_phase(20, code, 1.0)
		assert(stage.motion_phase == -1)
		assert(stage.phase_nodes.is_empty())
	stage.phase_graph.free()
	stage.free()
	print("PHASE_VIEW_OK stable_previous repeated_tick rewind invalid_codes graph_connections")
	quit(0)
