use brawllib_rs::high_level_fighter::HighLevelSubaction;
use crate::Trigger;

#[derive(Clone, Copy)]
pub struct TransitionSpec<'a> {
    pub from: &'a str,
    pub trigger: Trigger,
    pub to: &'a str,
}

fn action_index(actions: &[HighLevelSubaction], name: &str) -> Result<usize, String> {
    let matches: Vec<_> = actions.iter().enumerate()
        .filter_map(|(index, action)| (action.name == name).then_some(index))
        .collect();
    match matches.as_slice() {
        [index] => Ok(*index),
        [] => Err(format!("missing action {name}")),
        _ => Err(format!("duplicate action {name}")),
    }
}

pub fn emit_chart(
    actions: &[HighLevelSubaction],
    transitions: &[TransitionSpec<'_>],
) -> Result<String, String> {
    let mut output = String::from(
        "// Generated by smash-import. Do not edit.\n\nuse game_content::{Transition, Trigger};\n\n",
    );
    output.push_str(&format!("pub const TRANSITIONS: [Transition; {}] = [\n", transitions.len()));
    for transition in transitions {
        let from = action_index(actions, transition.from)?;
        let to = action_index(actions, transition.to)?;
        output.push_str(&format!(
            "    Transition {{ from: {from}, trigger: Trigger::{:?}, to: {to} }},\n",
            transition.trigger,
        ));
    }
    output.push_str("];\n");
    Ok(output)
}
