//! Bounded machine-macro lowering proof: one small transition-row declaration
//! expands into the existing `redux::Slice` behavior and derives debug graph
//! metadata from those same rows.
//!
//! # Generated vs authored
//!
//! - Generated by the local `machine!` macro: the zero-sized slice struct, its
//!   `Slice` implementation dispatch body (declared-row priority, guard
//!   fall-through, handled/unhandled results), and the `NODES`/`EDGES` graph
//!   constants. Rows are declared exactly once; the graph is derived from them,
//!   never maintained separately.
//! - Authored: state/event/context/effect types, named guard functions
//!   `fn(&State, Context) -> bool`, named action functions
//!   `fn(&mut State, Context, &mut impl FnMut(Effect))`, and the per-machine
//!   output enum. Guard and action bodies are ordinary Rust with no purity
//!   theorem; effects stay inert typed descriptors.
//!
//! All state is caller-owned plain serde data with Copy context; no second
//! state store, runtime interpreter, lifecycle hooks, or async reduction.
//! Restore is an exact value copy, so no entry hook can rerun.

use redux::{Slice, Then, Zoom};
use serde::{Deserialize, Serialize};

/// Shared graph metadata shape produced by `machine!` for every machine.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct Node {
    pub id: &'static str,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct Edge {
    pub id: &'static str,
    pub source: &'static str,
    pub event: &'static str,
    pub guard: Option<&'static str>,
    pub action: Option<&'static str>,
    pub target: &'static str,
}

/// Declare a machine: transition rows expand once into a `Slice` dispatch body
/// and into authored-name graph constants. Row priority is declaration order;
/// a false guard falls through to later rows and then to the unhandled result.
///
/// The lowering target is the existing `::redux::slice!` macro: `machine!`
/// emits one `slice!` invocation whose reduce body is generated from the rows,
/// so the zero-sized Slice and its associated types come from upstream code,
/// never duplicated here.
/// One graph edge per authored row. Comma placement inside the optional
/// groups lets the empty case fall to the plain arm, so absent guard/action
/// expand to `None` fields instead of a dangling `guard: ,`.
macro_rules! machine_edge {
    ($id:ident, $src:ident, $evt:ident, $tgt:ident) => {
        Edge {
            id: ::core::stringify!($id),
            source: ::core::stringify!($src),
            event: ::core::stringify!($evt),
            guard: ::core::option::Option::None,
            action: ::core::option::Option::None,
            target: ::core::stringify!($tgt),
        }
    };
    ($id:ident, $src:ident, $evt:ident, guard $g:ident, $tgt:ident) => {
        Edge {
            id: ::core::stringify!($id),
            source: ::core::stringify!($src),
            event: ::core::stringify!($evt),
            guard: ::core::option::Option::Some(::core::stringify!($g)),
            action: ::core::option::Option::None,
            target: ::core::stringify!($tgt),
        }
    };
    ($id:ident, $src:ident, $evt:ident, action $a:ident, $tgt:ident) => {
        Edge {
            id: ::core::stringify!($id),
            source: ::core::stringify!($src),
            event: ::core::stringify!($evt),
            guard: ::core::option::Option::None,
            action: ::core::option::Option::Some(::core::stringify!($a)),
            target: ::core::stringify!($tgt),
        }
    };
    ($id:ident, $src:ident, $evt:ident, guard $g:ident, action $a:ident, $tgt:ident) => {
        Edge {
            id: ::core::stringify!($id),
            source: ::core::stringify!($src),
            event: ::core::stringify!($evt),
            guard: ::core::option::Option::Some(::core::stringify!($g)),
            action: ::core::option::Option::Some(::core::stringify!($a)),
            target: ::core::stringify!($tgt),
        }
    };
}

macro_rules! machine {
    (
        $(#[$meta:meta])*
        $vis:vis $name:ident for $state:ty {
            context: $cx:ty, event: $ev:ty, phase: $phase:ident via $field:ident,
            effect: $eff:ty,
            output: $out:ty { handled: $hand:ident, unhandled: $un:ident },
            states: [ $($node:ident),+ $(,)? ],
            graph: { nodes: $nodes:ident, edges: $edges:ident },
            $( ( $src:ident, $evt:ident $(, guard: $g:ident)? $(, action: $a:ident)?, -> $tgt:ident, id: $id:ident ) ),* $(,)?
        }
    ) => {
        ::redux::slice! {
            $(#[$meta])*
            $vis $name for $state {
                context: $cx, event: $ev, output: $out, effect: $eff,
                reduce(st, ev, cx, fx) {
                    match (st.$field, ev) {
                        $(
                            (<$phase>::$src, <$ev>::$evt) $(if $g(st, cx))? => {
                                $( $a(st, cx, fx); )?
                                st.$field = <$phase>::$tgt;
                                <$out>::$hand
                            }
                        )*
                        _ => <$out>::$un,
                    }
                }
            }
        }
        $vis const $nodes: &[Node] = &[ $(Node { id: ::core::stringify!($node) }),+ ];
        $vis const $edges: &[Edge] = &[
            $( machine_edge!(
                $id, $src, $evt,
                $(guard $g,)?
                $(action $a,)?
                $tgt
            ) ),*
        ];
    };
}

// ---------------------------------------------------------------------------
// Model 1: grounded/airborne shared locomotion against a handwritten oracle.
// ---------------------------------------------------------------------------

/// Rollback state: one phase owner plus allowance and an unhandled tally.
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocoState {
    pub phase: LocoPhase,
    pub air_jumps_remaining: u8,
    pub unhandled_events: u32,
}

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocoPhase {
    #[default]
    Grounded,
    Airborne,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocoEvent {
    JumpPressed,
    SupportLost,
    Landed,
    Bump, // declared nowhere: exercises the unknown-input result
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocoCx {
    pub body: Body,
    pub max_air_jumps: u8,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Body(pub u32);

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Impulse {
    GroundJump,
    AirJump,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocoEffect {
    Apply { body: Body, impulse: Impulse },
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocoOutcome {
    Handled,
    Unhandled,
}

// Authored named guards and actions (ordinary Rust bodies).

fn has_air_jumps(st: &LocoState, _cx: LocoCx) -> bool {
    st.air_jumps_remaining > 0
}

fn takeoff(st: &mut LocoState, cx: LocoCx, fx: &mut impl FnMut(LocoEffect)) {
    st.air_jumps_remaining = cx.max_air_jumps;
    fx(LocoEffect::Apply {
        body: cx.body,
        impulse: Impulse::GroundJump,
    });
}

fn depart(st: &mut LocoState, cx: LocoCx, _fx: &mut impl FnMut(LocoEffect)) {
    st.air_jumps_remaining = cx.max_air_jumps;
}

fn land(st: &mut LocoState, _cx: LocoCx, _fx: &mut impl FnMut(LocoEffect)) {
    st.air_jumps_remaining = 0;
}

fn air_jump(st: &mut LocoState, cx: LocoCx, fx: &mut impl FnMut(LocoEffect)) {
    st.air_jumps_remaining -= 1;
    fx(LocoEffect::Apply {
        body: cx.body,
        impulse: Impulse::AirJump,
    });
}

machine! {
    /// Shared grounded/airborne machine; mirrors the `_3_shared_locomotion`
    /// base-layer semantics one row at a time.
    pub LocoMachine for LocoState {
        context: LocoCx, event: LocoEvent, phase: LocoPhase via phase,
        effect: LocoEffect,
        output: LocoOutcome { handled: Handled, unhandled: Unhandled },
        states: [Grounded, Airborne],
        graph: { nodes: LOCO_NODES, edges: LOCO_EDGES },
        (Grounded, JumpPressed, action: takeoff, -> Airborne, id: G_JUMP),
        (Grounded, SupportLost, action: depart, -> Airborne, id: G_DEPART),
        (Grounded, Landed, -> Grounded, id: G_LAND_SETTLED),
        (Airborne, Landed, action: land, -> Grounded, id: A_LAND),
        (Airborne, JumpPressed, guard: has_air_jumps, action: air_jump, -> Airborne, id: A_AIRJUMP),
    }
}

/// Handwritten oracle: same semantics, one authored match, no macro. The
/// machine must agree with this row for row.
fn oracle_loco(
    st: &mut LocoState,
    ev: LocoEvent,
    cx: LocoCx,
    fx: &mut impl FnMut(LocoEffect),
) -> LocoOutcome {
    match (st.phase, ev) {
        (LocoPhase::Grounded, LocoEvent::JumpPressed) => {
            takeoff(st, cx, fx);
            st.phase = LocoPhase::Airborne;
            LocoOutcome::Handled
        }
        (LocoPhase::Grounded, LocoEvent::SupportLost) => {
            depart(st, cx, fx);
            st.phase = LocoPhase::Airborne;
            LocoOutcome::Handled
        }
        (LocoPhase::Grounded, LocoEvent::Landed) => {
            st.phase = LocoPhase::Grounded;
            LocoOutcome::Handled
        }
        (LocoPhase::Airborne, LocoEvent::Landed) => {
            land(st, cx, fx);
            st.phase = LocoPhase::Grounded;
            LocoOutcome::Handled
        }
        (LocoPhase::Airborne, LocoEvent::JumpPressed) if has_air_jumps(st, cx) => {
            air_jump(st, cx, fx);
            st.phase = LocoPhase::Airborne;
            LocoOutcome::Handled
        }
        _ => LocoOutcome::Unhandled,
    }
}

/// Two addressed instances: each wrapper keeps machine state plus an unrelated
/// field that the shared machine must never touch.
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Fighter {
    pub loco: LocoState,
    pub damage: u8,
}

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Shooter {
    pub loco: LocoState,
    pub ammo: u8,
}

#[derive(Copy, Clone, Debug)]
struct FighterLoco;
impl redux::Lens<Fighter, LocoState> for FighterLoco {
    fn get(outer: &Fighter) -> &LocoState {
        &outer.loco
    }
    fn get_mut(outer: &mut Fighter) -> &mut LocoState {
        &mut outer.loco
    }
}

#[derive(Copy, Clone, Debug)]
struct ShooterLoco;
impl redux::Lens<Shooter, LocoState> for ShooterLoco {
    fn get(outer: &Shooter) -> &LocoState {
        &outer.loco
    }
    fn get_mut(outer: &mut Shooter) -> &mut LocoState {
        &mut outer.loco
    }
}

/// `Zoom` selects one instance's machine state inside the wrapper.
type FighterLocoSlice = Zoom<FighterLoco, LocoMachine, Fighter>;
type ShooterLocoSlice = Zoom<ShooterLoco, LocoMachine, Shooter>;

/// Result of one composed `Then` dispatch: resulting phase plus the deferred
/// event, preserving the existing None = consumed / Some(event) = deferred
/// contract from `_3_shared_locomotion`.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct LocoStep {
    pub phase: LocoPhase,
    pub deferred: Option<LocoEvent>,
}

/// Authored adapter in front of the generated machine: a Handled outcome
/// consumes the event (`None`); an Unhandled outcome defers the same event
/// unchanged (`Some(ev)`). Authored, ordinary Rust; the machine stays intact.
struct DeferredAdapter;

impl Slice for DeferredAdapter {
    type Context<'a> = LocoCx;
    type State = LocoState;
    type Event = LocoEvent;
    type Output = Option<LocoEvent>;
    type Effect = LocoEffect;

    fn reduce(
        st: &mut Self::State,
        ev: Self::Event,
        cx: Self::Context<'_>,
        fx: &mut impl FnMut(Self::Effect),
    ) -> Self::Output {
        match LocoMachine::reduce(st, ev, cx, fx) {
            LocoOutcome::Handled => None,
            LocoOutcome::Unhandled => Some(ev),
        }
    }
}

/// Fallback layer behind the adapter: sees `None` when the machine consumed
/// the event and no-ops on it; counts every deferred event. Emits no effects.
struct UnhandledTally;

impl Slice for UnhandledTally {
    type Context<'a> = LocoCx;
    type State = LocoState;
    type Event = Option<LocoEvent>;
    type Output = LocoStep;
    type Effect = LocoEffect;

    fn reduce(
        st: &mut Self::State,
        ev: Self::Event,
        _cx: Self::Context<'_>,
        _fx: &mut impl FnMut(Self::Effect),
    ) -> Self::Output {
        if let Some(deferred) = ev {
            st.unhandled_events += 1;
        }
        LocoStep {
            phase: st.phase,
            deferred: ev,
        }
    }
}

/// `Then` composition over the generated machine: A's outcome feeds B's event
/// while state, context and the effect sink stay shared.
type LocoThen = Then<DeferredAdapter, UnhandledTally>;

fn dispatch_fighter(st: &mut Fighter, ev: LocoEvent, cx: LocoCx) -> (LocoOutcome, Vec<LocoEffect>) {
    let mut fx = Vec::new();
    let out = FighterLocoSlice::reduce(st, ev, cx, &mut |e| fx.push(e));
    (out, fx)
}

fn dispatch_shooter(st: &mut Shooter, ev: LocoEvent, cx: LocoCx) -> (LocoOutcome, Vec<LocoEffect>) {
    let mut fx = Vec::new();
    let out = ShooterLocoSlice::reduce(st, ev, cx, &mut |e| fx.push(e));
    (out, fx)
}

// ---------------------------------------------------------------------------
// Model 2: menu / gameplay input-context machine.
// ---------------------------------------------------------------------------

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct MenuState {
    pub screen: MenuScreen,
    pub cursor: u8,
}

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum MenuScreen {
    #[default]
    NavList,
    ConfirmPlay,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum MenuEvent {
    Up,
    Down,
    Confirm,
    Back,
    Strike, // declared nowhere: unknown input
}

/// Copy input-context: item count gates the cursor guards.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MenuCx {
    pub items: u8,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum MenuEffect {
    Buzzer,
    Tick,
    EnterGame,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum MenuOutcome {
    Handled,
    Unhandled,
}

fn cursor_above_zero(st: &MenuState, _cx: MenuCx) -> bool {
    st.cursor > 0
}

fn cursor_below_last(st: &MenuState, cx: MenuCx) -> bool {
    (st.cursor as u32 + 1) < cx.items as u32
}

fn move_down(st: &mut MenuState, _cx: MenuCx, fx: &mut impl FnMut(MenuEffect)) {
    st.cursor += 1;
    fx(MenuEffect::Tick);
}

fn move_up(st: &mut MenuState, _cx: MenuCx, fx: &mut impl FnMut(MenuEffect)) {
    st.cursor = st.cursor.saturating_sub(1);
    fx(MenuEffect::Tick);
}

fn buzz(_st: &mut MenuState, _cx: MenuCx, fx: &mut impl FnMut(MenuEffect)) {
    fx(MenuEffect::Buzzer);
}

fn enter_game(_st: &mut MenuState, _cx: MenuCx, fx: &mut impl FnMut(MenuEffect)) {
    fx(MenuEffect::EnterGame);
}

machine! {
    /// Menu / gameplay input context: navigation with conditional self edges
    /// and a deterministic two-row Confirm priority (guard fall-through).
    pub MenuMachine for MenuState {
        context: MenuCx, event: MenuEvent, phase: MenuScreen via screen,
        effect: MenuEffect,
        output: MenuOutcome { handled: Handled, unhandled: Unhandled },
        states: [NavList, ConfirmPlay],
        graph: { nodes: MENU_NODES, edges: MENU_EDGES },
        (NavList, Up, guard: cursor_above_zero, action: move_up, -> NavList, id: NAV_UP),
        (NavList, Down, guard: cursor_below_last, action: move_down, -> NavList, id: NAV_DOWN),
        (NavList, Confirm, guard: cursor_below_last, action: buzz, -> NavList, id: NAV_CONFIRM_BUZZ),
        (NavList, Confirm, action: enter_game, -> ConfirmPlay, id: NAV_CONFIRM_PLAY),
        (NavList, Back, -> NavList, id: NAV_BACK_STAY),
        (ConfirmPlay, Back, action: buzz, -> NavList, id: CONFIRM_BACK),
        (ConfirmPlay, Confirm, action: enter_game, -> ConfirmPlay, id: CONFIRM_GO),
    }
}

/// `Zoom` selects the menu machine state inside the app wrapper.
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct App {
    pub menu: MenuState,
    pub credits: u16,
}

#[derive(Copy, Clone, Debug)]
struct MenuLens;
impl redux::Lens<App, MenuState> for MenuLens {
    fn get(outer: &App) -> &MenuState {
        &outer.menu
    }
    fn get_mut(outer: &mut App) -> &mut MenuState {
        &mut outer.menu
    }
}

type AppMenuSlice = Zoom<MenuLens, MenuMachine, App>;

fn dispatch_menu(st: &mut App, ev: MenuEvent, cx: MenuCx) -> (MenuOutcome, Vec<MenuEffect>) {
    let mut fx = Vec::new();
    let out = AppMenuSlice::reduce(st, ev, cx, &mut |e| fx.push(e));
    (out, fx)
}

fn main() {
    let fighter_cx = LocoCx {
        body: Body(2),
        max_air_jumps: 1,
    };
    let mut fighter = Fighter::default();
    for ev in [
        LocoEvent::JumpPressed,
        LocoEvent::Bump,
        LocoEvent::JumpPressed,
        LocoEvent::Landed,
    ] {
        let (out, fx) = dispatch_fighter(&mut fighter, ev, fighter_cx);
        println!("fighter {ev:?}: {out:?} fx={fx:?} state={fighter:?}");
    }
    let mut app = App::default();
    let menu_cx = MenuCx { items: 3 };
    for ev in [
        MenuEvent::Down,
        MenuEvent::Down,
        MenuEvent::Confirm,
        MenuEvent::Back,
        MenuEvent::Strike,
    ] {
        let (out, fx) = dispatch_menu(&mut app, ev, menu_cx);
        println!("menu {ev:?}: {out:?} fx={fx:?} state={app:?}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIGHTER_CX: LocoCx = LocoCx {
        body: Body(2),
        max_air_jumps: 1,
    };
    const SHOOTER_CX: LocoCx = LocoCx {
        body: Body(1),
        max_air_jumps: 0,
    };

    // ------------------------------------------------------------------
    // Graph metadata: derived from the same rows, asserted as literals.
    // ------------------------------------------------------------------

    #[test]
    fn loco_graph_nodes_and_edges_are_stable() {
        assert_eq!(
            LOCO_NODES,
            &[Node { id: "Grounded" }, Node { id: "Airborne" }]
        );
        assert_eq!(
            LOCO_EDGES,
            &[
                Edge {
                    id: "G_JUMP",
                    source: "Grounded",
                    event: "JumpPressed",
                    guard: None,
                    action: Some("takeoff"),
                    target: "Airborne",
                },
                Edge {
                    id: "G_DEPART",
                    source: "Grounded",
                    event: "SupportLost",
                    guard: None,
                    action: Some("depart"),
                    target: "Airborne",
                },
                Edge {
                    id: "G_LAND_SETTLED",
                    source: "Grounded",
                    event: "Landed",
                    guard: None,
                    action: None,
                    target: "Grounded",
                },
                Edge {
                    id: "A_LAND",
                    source: "Airborne",
                    event: "Landed",
                    guard: None,
                    action: Some("land"),
                    target: "Grounded",
                },
                // Conditional self edge: declared once, same rows as execution.
                Edge {
                    id: "A_AIRJUMP",
                    source: "Airborne",
                    event: "JumpPressed",
                    guard: Some("has_air_jumps"),
                    action: Some("air_jump"),
                    target: "Airborne",
                },
            ]
        );
    }

    #[test]
    fn menu_graph_nodes_and_edges_are_stable() {
        assert_eq!(
            MENU_NODES,
            &[Node { id: "NavList" }, Node { id: "ConfirmPlay" }]
        );
        let ids: Vec<&str> = MENU_EDGES.iter().map(|e| e.id).collect();
        assert_eq!(
            ids,
            [
                "NAV_UP",
                "NAV_DOWN",
                "NAV_CONFIRM_BUZZ",
                "NAV_CONFIRM_PLAY",
                "NAV_BACK_STAY",
                "CONFIRM_BACK",
                "CONFIRM_GO",
            ]
        );
        // Guard labels come from the authored guard names.
        let confirm_buzz = MENU_EDGES
            .iter()
            .find(|e| e.id == "NAV_CONFIRM_BUZZ")
            .unwrap();
        assert_eq!(confirm_buzz.guard, Some("cursor_below_last"));
        assert_eq!(confirm_buzz.source, "NavList");
        assert_eq!(confirm_buzz.target, "NavList", "conditional self edge");
        let confirm_play = MENU_EDGES
            .iter()
            .find(|e| e.id == "NAV_CONFIRM_PLAY")
            .unwrap();
        assert_eq!(confirm_play.guard, None, "lower-priority unguarded row");
    }

    /// Every declared edge is reachable: drive the machine into each source
    /// state with the guard passing, dispatch the event, and require the
    /// declared target and a Handled result. The graph describes conditional
    /// possibilities; each edge here is proven to fire at least once.
    #[test]
    fn every_declared_loco_edge_fires() {
        let mut st = LocoState::default();
        let mut fx = Vec::new();
        // G_JUMP
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::JumpPressed, FIGHTER_CX, &mut |e| fx
                .push(e)),
            LocoOutcome::Handled
        );
        assert_eq!(st.phase, LocoPhase::Airborne);
        // A_AIRJUMP (conditional self edge, guard passing)
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::JumpPressed, FIGHTER_CX, &mut |e| fx
                .push(e)),
            LocoOutcome::Handled
        );
        assert_eq!(st.phase, LocoPhase::Airborne);
        // A_LAND
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::Landed, FIGHTER_CX, &mut |e| fx.push(e)),
            LocoOutcome::Handled
        );
        assert_eq!(st.phase, LocoPhase::Grounded);
        // G_LAND_SETTLED (handled no-op self)
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::Landed, FIGHTER_CX, &mut |e| fx.push(e)),
            LocoOutcome::Handled
        );
        assert_eq!(st.phase, LocoPhase::Grounded);
        // G_DEPART
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::SupportLost, FIGHTER_CX, &mut |e| fx
                .push(e)),
            LocoOutcome::Handled
        );
        assert_eq!(st.phase, LocoPhase::Airborne);
        assert_eq!(
            fx,
            vec![
                LocoEffect::Apply {
                    body: Body(2),
                    impulse: Impulse::GroundJump
                },
                LocoEffect::Apply {
                    body: Body(2),
                    impulse: Impulse::AirJump
                },
            ]
        );
    }

    #[test]
    fn every_declared_menu_edge_fires() {
        let mut app = App::default();
        let cx = MenuCx { items: 3 };
        let mut outs = Vec::new();
        let mut fx = Vec::new();
        let mut step = |app: &mut App, ev| {
            let (out, effects) = dispatch_menu(app, ev, cx);
            outs.push(out);
            fx.extend(effects);
            out
        };
        // NAV_CONFIRM_BUZZ: guard true (cursor 0 < items 3): buzz and stay.
        assert_eq!(step(&mut app, MenuEvent::Confirm), MenuOutcome::Handled);
        assert_eq!(app.menu.screen, MenuScreen::NavList);
        // NAV_DOWN, NAV_UP
        assert_eq!(step(&mut app, MenuEvent::Down), MenuOutcome::Handled);
        assert_eq!(app.menu.cursor, 1);
        assert_eq!(step(&mut app, MenuEvent::Up), MenuOutcome::Handled);
        assert_eq!(app.menu.cursor, 0);
        // NAV_CONFIRM_PLAY: cursor at last item -> guard false falls through.
        app.menu.cursor = 2;
        assert_eq!(step(&mut app, MenuEvent::Confirm), MenuOutcome::Handled);
        assert_eq!(app.menu.screen, MenuScreen::ConfirmPlay);
        // CONFIRM_GO (handled self)
        assert_eq!(step(&mut app, MenuEvent::Confirm), MenuOutcome::Handled);
        assert_eq!(app.menu.screen, MenuScreen::ConfirmPlay);
        // CONFIRM_BACK
        assert_eq!(step(&mut app, MenuEvent::Back), MenuOutcome::Handled);
        assert_eq!(app.menu.screen, MenuScreen::NavList);
        // NAV_BACK_STAY (handled self, no action)
        assert_eq!(step(&mut app, MenuEvent::Back), MenuOutcome::Handled);
        assert_eq!(app.menu.screen, MenuScreen::NavList);
        assert_eq!(outs, vec![MenuOutcome::Handled; 7]);
        assert_eq!(
            fx,
            vec![
                MenuEffect::Buzzer,
                MenuEffect::Tick,
                MenuEffect::Tick,
                MenuEffect::EnterGame,
                MenuEffect::EnterGame,
                MenuEffect::Buzzer,
            ]
        );
    }

    // ------------------------------------------------------------------
    // Handled / unhandled / guard rejection / priority.
    // ------------------------------------------------------------------

    #[test]
    fn guard_rejection_is_unhandled_without_effects() {
        let mut st = LocoState {
            phase: LocoPhase::Airborne,
            ..LocoState::default()
        };
        st.air_jumps_remaining = 0; // guard fails: nothing left
        let mut fx = Vec::new();
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::JumpPressed, FIGHTER_CX, &mut |e| fx
                .push(e)),
            LocoOutcome::Unhandled
        );
        assert!(fx.is_empty());
        assert_eq!(
            st.phase,
            LocoPhase::Airborne,
            "unhandled event must not move the phase"
        );
    }

    #[test]
    fn undeclared_state_event_and_unknown_event_are_unhandled() {
        let mut st = LocoState::default();
        let mut fx = Vec::new();
        // Airborne SupportLost is declared by no row.
        st.phase = LocoPhase::Airborne;
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::SupportLost, FIGHTER_CX, &mut |e| fx
                .push(e)),
            LocoOutcome::Unhandled
        );
        assert_eq!(st.phase, LocoPhase::Airborne);
        // Unknown input: Bump is declared nowhere in either machine.
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::Bump, FIGHTER_CX, &mut |e| fx.push(e)),
            LocoOutcome::Unhandled
        );
        let mut app = App::default();
        let (out, fx_menu) = dispatch_menu(&mut app, MenuEvent::Strike, MenuCx { items: 2 });
        assert_eq!(out, MenuOutcome::Unhandled);
        assert_eq!(app.menu.screen, MenuScreen::NavList);
        assert!(fx_menu.is_empty());
    }

    #[test]
    fn handled_self_transition_differs_from_unhandled() {
        let mut st = LocoState {
            phase: LocoPhase::Airborne,
            air_jumps_remaining: 1,
            unhandled_events: 0,
        };
        let mut fx = Vec::new();
        // Handled self: same variant, real action and effect.
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::JumpPressed, FIGHTER_CX, &mut |e| fx
                .push(e)),
            LocoOutcome::Handled
        );
        assert_eq!(st.phase, LocoPhase::Airborne);
        assert_eq!(
            fx,
            vec![LocoEffect::Apply {
                body: Body(2),
                impulse: Impulse::AirJump
            }]
        );
        // Unhandled self: guard now false, nothing happens.
        assert_eq!(
            LocoMachine::reduce(&mut st, LocoEvent::JumpPressed, FIGHTER_CX, &mut |e| fx
                .push(e)),
            LocoOutcome::Unhandled
        );
        assert_eq!(fx.len(), 1, "no second effect");
    }

    #[test]
    fn menu_confirm_priority_falls_through_on_guard_failure() {
        let mut app = App::default();
        let cx = MenuCx { items: 3 };
        // Guard true: first row wins, buzz and stay.
        let (out, fx) = dispatch_menu(&mut app, MenuEvent::Confirm, cx);
        assert_eq!(out, MenuOutcome::Handled);
        assert_eq!(app.menu.screen, MenuScreen::NavList);
        assert_eq!(fx, vec![MenuEffect::Buzzer]);
        // Guard false: first row rejected, execution falls to the second row.
        app.menu.cursor = 2;
        let (out, fx) = dispatch_menu(&mut app, MenuEvent::Confirm, cx);
        assert_eq!(out, MenuOutcome::Handled);
        assert_eq!(app.menu.screen, MenuScreen::ConfirmPlay);
        assert_eq!(fx, vec![MenuEffect::EnterGame]);
    }

    // ------------------------------------------------------------------
    // Oracle parity over tapes: exact outcomes and effect vectors.
    // ------------------------------------------------------------------

    #[test]
    fn machine_matches_handwritten_oracle_over_tapes() {
        let tapes: &[&[LocoEvent]] = &[
            &[
                LocoEvent::JumpPressed,
                LocoEvent::JumpPressed,
                LocoEvent::JumpPressed,
                LocoEvent::Landed,
            ],
            &[
                LocoEvent::SupportLost,
                LocoEvent::JumpPressed,
                LocoEvent::SupportLost,
                LocoEvent::Landed,
            ],
            &[LocoEvent::Bump, LocoEvent::Landed, LocoEvent::Bump],
            &[LocoEvent::Landed, LocoEvent::Landed],
        ];
        for tape in tapes {
            let mut machine_st = LocoState::default();
            let mut oracle_st = LocoState::default();
            let mut machine_out = Vec::new();
            let mut machine_fx = Vec::new();
            let mut oracle_out = Vec::new();
            let mut oracle_fx = Vec::new();
            for ev in *tape {
                machine_out.push(LocoMachine::reduce(
                    &mut machine_st,
                    *ev,
                    FIGHTER_CX,
                    &mut |e| machine_fx.push(e),
                ));
                oracle_out.push(oracle_loco(&mut oracle_st, *ev, FIGHTER_CX, &mut |e| {
                    oracle_fx.push(e)
                }));
            }
            assert_eq!(machine_out, oracle_out, "outcomes");
            assert_eq!(machine_fx, oracle_fx, "exact effect vectors");
            assert_eq!(machine_st, oracle_st, "final durable state");
        }
    }

    #[test]
    fn loco_tape_effect_vector_is_exact() {
        let mut st = LocoState::default();
        let tape = [
            LocoEvent::JumpPressed,
            LocoEvent::JumpPressed,
            LocoEvent::Bump,
            LocoEvent::Landed,
        ];
        let mut outs = Vec::new();
        let mut fx = Vec::new();
        for ev in tape {
            outs.push(LocoMachine::reduce(&mut st, ev, FIGHTER_CX, &mut |e| {
                fx.push(e)
            }));
        }
        assert_eq!(
            outs,
            vec![
                LocoOutcome::Handled,
                LocoOutcome::Handled,
                LocoOutcome::Unhandled,
                LocoOutcome::Handled
            ]
        );
        assert_eq!(
            fx,
            vec![
                LocoEffect::Apply {
                    body: Body(2),
                    impulse: Impulse::GroundJump
                },
                LocoEffect::Apply {
                    body: Body(2),
                    impulse: Impulse::AirJump
                },
            ]
        );
        assert_eq!(
            st,
            LocoState {
                phase: LocoPhase::Grounded,
                air_jumps_remaining: 0,
                unhandled_events: 0
            }
        );
    }

    // ------------------------------------------------------------------
    // Two addressed instances via Zoom; unrelated fields untouched.
    // ------------------------------------------------------------------

    #[test]
    fn two_addressed_instances_preserve_unrelated_fields() {
        let mut fighter = Fighter {
            loco: LocoState::default(),
            damage: 73,
        };
        let mut shooter = Shooter {
            loco: LocoState::default(),
            ammo: 9,
        };
        let (f_out, f_fx) = dispatch_fighter(&mut fighter, LocoEvent::JumpPressed, FIGHTER_CX);
        assert_eq!(f_out, LocoOutcome::Handled);
        assert_eq!(
            f_fx,
            vec![LocoEffect::Apply {
                body: Body(2),
                impulse: Impulse::GroundJump
            }]
        );
        assert_eq!(
            shooter.loco,
            LocoState::default(),
            "untouched instance must not move"
        );
        assert_eq!(fighter.damage, 73);
        let (s_out, s_fx) = dispatch_shooter(&mut shooter, LocoEvent::JumpPressed, SHOOTER_CX);
        assert_eq!(s_out, LocoOutcome::Handled);
        assert_eq!(
            s_fx,
            vec![LocoEffect::Apply {
                body: Body(1),
                impulse: Impulse::GroundJump
            }]
        );
        assert_eq!(shooter.ammo, 9);
        assert_ne!(
            fighter.loco.air_jumps_remaining, shooter.loco.air_jumps_remaining,
            "config differs: fighter 1, shooter 0"
        );
    }

    #[test]
    fn shooter_cannot_air_jump() {
        let mut shooter = Shooter::default();
        let (_, fx) = dispatch_shooter(&mut shooter, LocoEvent::JumpPressed, SHOOTER_CX);
        let (out, fx2) = dispatch_shooter(&mut shooter, LocoEvent::JumpPressed, SHOOTER_CX);
        assert_eq!(out, LocoOutcome::Unhandled);
        assert_eq!(fx.len(), 1);
        assert!(fx2.is_empty());
        assert_eq!(shooter.loco.air_jumps_remaining, 0);
    }

    // ------------------------------------------------------------------
    // Clone AND serde suffix restoration vs one uninterrupted reference.
    // ------------------------------------------------------------------

    fn run_fighter_tape(
        st: &mut Fighter,
        tape: &[LocoEvent],
    ) -> (Vec<LocoOutcome>, Vec<LocoEffect>) {
        let mut outs = Vec::new();
        let mut fx = Vec::new();
        for ev in tape {
            let (out, effects) = dispatch_fighter(st, *ev, FIGHTER_CX);
            outs.push(out);
            fx.extend(effects);
        }
        (outs, fx)
    }

    #[test]
    fn clone_and_serde_suffix_restoration_equals_reference() {
        let prefix = [LocoEvent::JumpPressed, LocoEvent::JumpPressed];
        let suffix = [
            LocoEvent::Landed,
            LocoEvent::JumpPressed,
            LocoEvent::SupportLost,
            LocoEvent::Bump,
        ];
        let mut full = Vec::new();
        full.extend(prefix);
        full.extend(suffix);

        // Reference: one uninterrupted run; record the suffix slice at the
        // prefix boundary, independent of any restored run.
        let mut reference = Fighter::default();
        run_fighter_tape(&mut reference, &prefix);
        let (fresh_outs, fresh_fx) = run_fighter_tape(&mut reference, &suffix);
        assert!(!fresh_fx.is_empty(), "reference suffix must emit commands");

        // Clone restore: no effects, no hooks.
        let mut original = Fighter::default();
        run_fighter_tape(&mut original, &prefix);
        let mut cloned = original;
        let (clone_outs, clone_fx) = run_fighter_tape(&mut cloned, &suffix);

        // Serde restore: exact value copy, no entry hook can rerun.
        let bytes = serde_json::to_vec(&original).unwrap();
        let mut decoded: Fighter = serde_json::from_slice(&bytes).unwrap();
        let (serde_outs, serde_fx) = run_fighter_tape(&mut decoded, &suffix);

        assert_eq!(cloned, reference, "clone restores the full durable state");
        assert_eq!(decoded, reference, "serde restores the full durable state");
        assert_eq!(
            fresh_outs, clone_outs,
            "exact vectors, not length-derived slices"
        );
        assert_eq!(fresh_outs, serde_outs);
        assert_eq!(fresh_fx, clone_fx);
        assert_eq!(fresh_fx, serde_fx);
        assert_eq!(full.len(), prefix.len() + suffix.len());
    }

    // ------------------------------------------------------------------
    // Menu model over an addressed instance: serde restoration too.
    // ------------------------------------------------------------------

    #[test]
    fn menu_serde_restore_equals_reference() {
        let cx = MenuCx { items: 3 };
        let prefix = [MenuEvent::Down, MenuEvent::Down];
        let suffix = [MenuEvent::Back, MenuEvent::Confirm, MenuEvent::Strike];
        let step = |app: &mut App, tape: &[MenuEvent]| {
            let mut outs = Vec::new();
            let mut fx = Vec::new();
            for ev in tape {
                let (out, effects) = dispatch_menu(app, *ev, cx);
                outs.push(out);
                fx.extend(effects);
            }
            (outs, fx)
        };
        let mut reference = App::default();
        let _ = step(&mut reference, &prefix);
        let (fresh_outs, fresh_fx) = step(&mut reference, &suffix);

        let mut original = App::default();
        let _ = step(&mut original, &prefix);
        let bytes = serde_json::to_vec(&original).unwrap();
        let mut decoded: App = serde_json::from_slice(&bytes).unwrap();
        let (serde_outs, serde_fx) = step(&mut decoded, &suffix);

        assert_eq!(decoded, reference);
        assert_eq!(fresh_outs, serde_outs);
        assert_eq!(fresh_fx, serde_fx);
    }

    // ------------------------------------------------------------------
    // Then composition: None = consumed, Some(event) = deferred.
    // ------------------------------------------------------------------

    #[test]
    fn then_composition_defers_only_unhandled_events() {
        let mut st = LocoState::default();
        let mut outs = Vec::new();
        let mut fx = Vec::new();
        let tape = [
            LocoEvent::JumpPressed, // Grounded->Airborne: handled, consumed
            LocoEvent::JumpPressed, // guarded handled self: consumed, must NOT reach fallback
            LocoEvent::JumpPressed, // guard-rejected self: deferred unchanged
            LocoEvent::Bump,        // unknown input: deferred unchanged
            LocoEvent::Landed,      // Airborne->Grounded: handled, consumed
            LocoEvent::Landed,      // handled self (G_LAND_SETTLED): consumed
            LocoEvent::SupportLost, // Airborne SupportLost: undeclared, deferred
        ];
        for ev in tape {
            outs.push(LocoThen::reduce(&mut st, ev, FIGHTER_CX, &mut |e| {
                fx.push(e)
            }));
        }
        assert_eq!(
            outs,
            vec![
                LocoStep {
                    phase: LocoPhase::Airborne,
                    deferred: None
                },
                LocoStep {
                    phase: LocoPhase::Airborne,
                    deferred: None
                },
                LocoStep {
                    phase: LocoPhase::Airborne,
                    deferred: Some(LocoEvent::JumpPressed)
                },
                LocoStep {
                    phase: LocoPhase::Airborne,
                    deferred: Some(LocoEvent::Bump)
                },
                LocoStep {
                    phase: LocoPhase::Grounded,
                    deferred: None
                },
                LocoStep {
                    phase: LocoPhase::Grounded,
                    deferred: None
                },
                // State is Grounded here: SupportLost is the declared G_DEPART edge.
                LocoStep {
                    phase: LocoPhase::Airborne,
                    deferred: None
                },
            ],
            "handled self and transitions consume; guard-rejected and unknown events defer unchanged"
        );
        // Exact ordered effects: only machine actions emit; the fallback layer adds none.
        assert_eq!(
            fx,
            vec![
                LocoEffect::Apply {
                    body: Body(2),
                    impulse: Impulse::GroundJump
                },
                LocoEffect::Apply {
                    body: Body(2),
                    impulse: Impulse::AirJump
                },
            ]
        );
        // Full state: only the guard-rejected JumpPressed and the unknown Bump
        // reached the fallback; the SupportLost departure was handled upstream.
        assert_eq!(st.unhandled_events, 2);
        // G_DEPART re-initialized the allowance on the final departure.
        assert_eq!(st.air_jumps_remaining, 1);
        assert_eq!(st.phase, LocoPhase::Airborne);
    }

    // ------------------------------------------------------------------
    // Graph shape: unique ids, every endpoint declared in nodes.
    // ------------------------------------------------------------------

    fn assert_graph_shape(nodes: &[Node], edges: &[Edge], event_domain: &[&str]) {
        let mut node_ids: Vec<&str> = nodes.iter().map(|n| n.id).collect();
        node_ids.sort_unstable();
        let node_count = node_ids.len();
        node_ids.dedup();
        assert_eq!(node_ids.len(), node_count, "node ids must be unique");

        let mut edge_ids: Vec<&str> = edges.iter().map(|e| e.id).collect();
        edge_ids.sort_unstable();
        let edge_count = edge_ids.len();
        edge_ids.dedup();
        assert_eq!(edge_ids.len(), edge_count, "edge ids must be unique");

        for edge in edges {
            assert!(
                nodes.iter().any(|n| n.id == edge.source),
                "edge {} source {} is not a declared node",
                edge.id,
                edge.source
            );
            assert!(
                nodes.iter().any(|n| n.id == edge.target),
                "edge {} target {} is not a declared node",
                edge.id,
                edge.target
            );
            assert!(
                event_domain.contains(&edge.event),
                "edge {} event {} is outside the event domain",
                edge.id,
                edge.event
            );
        }
    }

    #[test]
    fn loco_graph_ids_are_unique_and_endpoints_declared() {
        assert_graph_shape(
            LOCO_NODES,
            LOCO_EDGES,
            &["JumpPressed", "SupportLost", "Landed", "Bump"],
        );
    }

    #[test]
    fn menu_graph_ids_are_unique_and_endpoints_declared() {
        assert_graph_shape(
            MENU_NODES,
            MENU_EDGES,
            &["Up", "Down", "Confirm", "Back", "Strike"],
        );
    }
}
