extends SceneTree

func _initialize():
	var stage = load("res://2_stage.gd").new()
	stage.phase_graph = GraphEdit.new()
	root.add_child(stage.phase_graph)
	stage._observe_phase(10, 0.0, 1.0)
	stage._observe_phase(11, 2.0, 1.0)
	stage._observe_phase(12, 2.0, 2.0)
	assert(stage.previous_motion_phase == 0)
	assert(stage.motion_enter_tick == 11)
	assert(stage.observed_edges.keys() == ["IDLE->DASH"])
	assert(stage.phase_graph.get_connection_list().size() == 1)
	assert(stage.phase_nodes[2].title == "▶ DASH ←")
	assert(stage.phase_nodes[0].title == "IDLE")
	assert(stage.phase_nodes[0].position_offset == stage.phase_graph_cell(0))
	assert(stage.phase_nodes[2].position_offset == stage.phase_graph_cell(2))
	assert(stage.phase_nodes[0].position_offset != stage.phase_nodes[2].position_offset)
	assert(stage.phase_nodes[2].self_modulate != stage.phase_nodes[0].self_modulate)
	stage._observe_phase(12, 2.0, 2.0)
	assert(stage.observed_edges.size() == 1)
	stage._observe_phase(13, 2.0, 1.0)
	assert(stage.previous_motion_phase == 2)
	assert(stage.motion_enter_tick == 13)
	assert(stage.observed_edges == {"IDLE->DASH": 1, "DASH->DASH": 1})
	assert(stage.phase_graph.get_connection_list().size() == 2)
	assert(stage.phase_nodes[2].get_child(0).text == "entered T13 / re-entry")
	stage._observe_phase(13, 2.0, 1.0)
	stage._observe_phase(14, 2.0, 2.0)
	assert(stage.observed_edges["DASH->DASH"] == 1)
	stage._observe_phase(12, 3.0, 1.0)
	assert(stage.observed_edges.is_empty())
	assert(stage.phase_graph.get_connection_list().is_empty())
	stage._observe_phase(8, 0.0, 1.0)
	assert(stage.previous_motion_phase == -1)
	assert(stage.phase_nodes.keys() == [0])
	assert(stage.newest_phase == -1)
	assert(stage.phase_nodes[0].title == "▶ IDLE")
	for code in [-1.0, 12.0, 0.5, NAN, INF]:
		stage._observe_phase(20, code, 1.0)
		assert(stage.motion_phase == -1)
		assert(stage.phase_nodes.is_empty())
	stage.phase_graph.free()
	stage.free()
	print("PHASE_VIEW_OK stable_previous repeated_tick rewind invalid_codes graph_connections")
	quit(0)
