[workspace]
resolver = "3"

[package]
name = "falcon_web"
version = "0.1.0"
edition = "2024"

[lib]
path = "0_lib.rs"
crate-type = ["cdylib"]

[dependencies]
smash = { path = "../../../smash" }
core-labs = { path = "../../core-labs", default-features = false }
godot = { version = "=0.4.5", default-features = false }
rusqlite = { version = "=0.40.2", features = ["bundled", "vtab"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = { version = "2", features = ["serde"] }
tracing = "=0.1.44"
cgmath = "0.18"
parry3d = "=0.30.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
godot = { version = "=0.4.5", default-features = false, features = ["api-custom", "experimental-wasm", "lazy-function-tables"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
godot = { version = "=0.4.5", default-features = false, features = ["api-4-5"] }

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = "debuginfo"
